version: '3'
services:
  angular_app:
    restart: always
    build: ./frontend
    volumes:
      - ./frontend/dist/lab4:/usr/share/nginx/html
    ports:
      - "4200:80"
    depends_on:
      - web_app_spring
  web_app_spring:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    container_name: web_app_spring
  mongo:
    image: mongo
    ports:
      - "27017:27017"