version: '3'
services:
  web-rest:
    image: pedibus:latest
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    container_name: pedibus-server
  mongo:
    image: mongo
    ports:
      - "27017:27017"