PUT http://localhost:8080/reservations/Line1/20190415/5cd4411b18c0271b94c0dca5
Content-Type: application/json

{
  "lineName": "Line1",
  "stopName": "Stop2",
  "flagAndata": "true",
  "reservationDate": "2019/04/15",
  "passenger": {
    "name": "jeanpiero",
    "surname": "francois",
    "registrationNumber": "jpf"
  }
}

###